### ISSUE TITLE
Create docker image for this, so we can easily use it in buildpipelines.

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/ct2r#5]
Create docker image for it so we can easily use it in buildpipelines.

Now we have to clone the repository, build it and run the script.

f.e. part of gitlab yaml:
```
convert:
  stage: convert
  image: rust
  script:
    - git clone https://github.com/philips-software/ct2r.git
    - cd ct2r
    - cargo build --release
    - ./target/release/ct2r gradle ../build/reports/dependency-license/index.json
    - cp output.json ..
    - cat output.json
  artifacts:
    untracked: true
```

More convient would be:
```
convert:
  stage: convert
  image: philipssoftware/ct2r
  script:
    - ct2r gradle ./build/reports/dependency-license/index.json
  artifacts:
    untracked: true
```
